INSERT INTO public.website_content (page, section_key, sort_order, is_visible, content)
VALUES
('privacy-policy', 'legal_document', 0, true, jsonb_build_object(
  'layout', 'legal_document',
  'title', 'Privacy Policy — Max-IR Labs',
  'effective_date', 'Effective Date: March 25, 2026 · Last Updated: April 21, 2026',
  'intro', 'Max-IR Labs ("we," "us," or "our"), incorporated in Texas, USA, is committed to protecting the privacy of users of our website. This Privacy Statement applies to our online services and describes the information we collect about users and how that information may be used to facilitate the purchase of products, provide requested technical information, or fulfill service requests.',
  'sections', jsonb_build_array(
    jsonb_build_object('heading','1. Information Collection','body','<p>We collect two types of information to provide our services:</p><ul><li><strong>Personally Identifiable Information (PII):</strong> This includes information you voluntarily provide, such as your name, email address, professional affiliation, shipping/billing address, and phone number when placing an order or requesting a quote.</li><li><strong>Aggregate Information:</strong> This is non-identifying, anonymous data (such as IP addresses, browser types, and page visit frequency) automatically logged by our website hosting and payment platforms (e.g., Squarespace, Stripe). This data is used in a collective manner to analyze site performance and cannot be used to identify you individually.</li></ul>'),
    jsonb_build_object('heading','2. Cookies and Similar Technologies','body','<p>This section describes the cookies and similar device-storage technologies (such as localStorage) used on this website, and how you can manage them. You can change your choices at any time by clicking "Cookie Settings" in the footer.</p><h3>2.1 Categories of cookies we use</h3><p><strong>Strictly Necessary (always active).</strong> These cookies are required for core functionality — authentication, shopping cart, secure checkout, and remembering your cookie choices. The site cannot function without them, and they do not require consent under applicable law.</p><ul><li><strong>Authentication (Supabase):</strong> <code>sb-access-token</code>, <code>sb-refresh-token</code> — keep you signed in during a session.</li><li><strong>Shopping cart (Max-IR Labs):</strong> <code>cart_state</code> — remembers items in your cart.</li><li><strong>Checkout security (Stripe):</strong> <code>__stripe_mid</code>, <code>__stripe_sid</code> — fraud prevention during payment.</li><li><strong>Consent preferences (Max-IR Labs):</strong> <code>consent_state</code> — remembers the cookie choices you have made.</li></ul><p><strong>Functional, Analytics, and Advertising cookies.</strong> We do not currently use any functional, analytics, or advertising cookies. If this changes in the future, those cookies will only be set after you have given explicit consent through the cookie settings. You can review the current list of cookies by category at any time via "Cookie Settings".</p><h3>2.2 Your choices</h3><p>On your first visit from the EU, UK, or European Economic Area, a cookie banner lets you accept, reject, or customize non-essential cookies. Visitors from other regions can manage the same choices at any time via the "Cookie Settings" link in the footer. You can also control cookies through your browser settings, though disabling strictly necessary cookies may prevent parts of the site (such as the shopping cart or sign-in) from working.</p><h3>2.3 California residents</h3><p>If you are a California resident, you have the right to opt out of the "sale" or "sharing" of your personal information under the CCPA/CPRA. We currently do not sell or share personal information for cross-context behavioral advertising. If this changes, you will be able to exercise this right via the "Do Not Sell or Share My Personal Information" link in the footer, and we will honor browser-level Global Privacy Control (GPC) signals as valid opt-out requests.</p><h3>2.4 Retention of consent records</h3><p>When you make a cookie choice, we log a record consisting of a timestamp, the choices you made, and the version of this policy in effect at that time. This record is kept to demonstrate compliance with data protection law, as required by GDPR Article 7(1). Your consent is valid for 12 months, after which we will ask you again.</p>'),
    jsonb_build_object('heading','3. How We Use Your Information','body','<p>We use your data strictly for business-related purposes, including:</p><ul><li>Fulfilling and shipping orders for our products.</li></ul>'),
    jsonb_build_object('heading','4. Onward Transfer to Third Parties','body','<p>Max-IR Labs does not sell, rent, or lease your personal information. We only share data with essential third-party service providers to complete your transactions:</p><ul><li><strong>Shipping Carriers:</strong> (e.g., FedEx, UPS) to deliver products to your location.</li><li><strong>Payment Processors:</strong> (e.g., Stripe, Square) to securely handle credit card data.</li><li><strong>Compliance:</strong> We may disclose information to government officials if required by legal obligations, including subpoenas, court orders, or to meet national security and export control requirements.</li></ul><p>These third parties are prohibited from using your information for any purpose other than providing these specific services to Max-IR Labs.</p>'),
    jsonb_build_object('heading','5. Data Security','body','<p>We implement physical, electronic, and managerial procedures to safeguard your information. All sensitive transaction data is encrypted during transfer. While we take commercially reasonable efforts to secure your data, please be aware that no transmission over the internet is 100% secure.</p>'),
    jsonb_build_object('heading','6. Your Rights & Access','body','<p>Regardless of your global location, you have the right to:</p><ul><li>Request a copy of the personal data we hold about you.</li><li>Request the correction of inaccurate information.</li><li>Request the deletion of your data, subject to our legal requirements for tax and trade record retention.</li></ul>'),
    jsonb_build_object('heading','7. Contact Us','body','<p>For questions regarding this Privacy Policy or to exercise your data rights, please contact:</p><address>Max-IR Labs<br/>17217 Waterview Pkwy<br/>Suite 1.202<br/>Dallas, TX, 75252<br/>Email: <a href="mailto:privacy@max-ir-labs.com">privacy@max-ir-labs.com</a></address>')
  )
)),
('refund-and-return', 'legal_document', 0, true, jsonb_build_object(
  'layout', 'legal_document',
  'title', 'Refund & Return Policy',
  'effective_date', 'Effective Date: March 25, 2026',
  'intro', 'Max-IR Labs is committed to providing high-performance optical solutions. We understand that technical requirements may change, and we strive to make our return process as transparent as possible for our global customers.',
  'sections', jsonb_build_array(
    jsonb_build_object('heading','1. Return Authorization (RMA)','body','<p>No returns will be accepted without a Return Material Authorization (RMA) number.</p><ul><li><strong>To Request:</strong> Contact <a href="mailto:sales@max-ir-labs.com">sales@max-ir-labs.com</a> with your original Purchase Order or Sales Order number as proof of purchase.</li><li><strong>Deadline:</strong> Approved RMA numbers are valid for 30 days from the date of issue. Products must be received at our Dallas facility within this window.</li><li><strong>Labeling:</strong> The RMA number must be clearly marked on the outside of the shipping package for immediate identification.</li></ul>'),
    jsonb_build_object('heading','2. Standard Products & Consumables','body','<p>Standard catalog items are eligible for a refund within 30 days of purchase, subject to the following technical requirements:</p><ul><li><strong>Sealed Condition:</strong> Products must be returned unopened, in their original vacuum-sealed or protective packaging, with all paperwork intact.</li><li><strong>Opened Items:</strong> Due to the risk of environmental degradation and contamination, returns are not accepted for any optical components or consumables once the protective packaging has been opened.</li><li><strong>Restocking Fee:</strong> Approved returns for credit may be subject to a 15% restocking fee to cover technical inspection and re-certification.</li></ul>'),
    jsonb_build_object('heading','3. Custom and Special Orders','body','<p><strong>Final Sale:</strong> Any custom-configured products, modified items, or "specials" built to Buyer specifications are not eligible for return or refund.</p><p><strong>Warranty:</strong> These items are covered strictly under the repair/replacement terms found in our Terms & Conditions.</p>'),
    jsonb_build_object('heading','4. Health and Safety Restrictions','body','<p><strong>Strict Non-Return Policy:</strong> Any products that have come into contact with biological specimens, radioactive materials, or hazardous chemicals cannot be returned under any circumstances. Customers may be required to sign a decontamination declaration before an RMA is issued for equipment that has been utilized in a laboratory environment.</p>'),
    jsonb_build_object('heading','5. Shipping and Costs','body','<ul><li><strong>Responsibility:</strong> The Buyer is responsible for all return shipping charges, including international customs, duties, and insurance.</li><li><strong>Risk:</strong> Risk of loss for returned items remains with the Buyer until the package is physically received and signed for by Max-IR Labs.</li></ul>'),
    jsonb_build_object('heading','6. Processing','body','<p>Refunds are processed to the original payment method within 10 business days of receipt and successful technical inspection.</p>')
  )
)),
('shipping-policy', 'legal_document', 0, true, jsonb_build_object(
  'layout', 'legal_document',
  'title', 'Shipping & Delivery Policy',
  'effective_date', 'Effective Date: March 25, 2026',
  'intro', '',
  'sections', jsonb_build_array(
    jsonb_build_object('heading','1. Delivery Timelines','body','<p>Max-IR Labs will use reasonable endeavors to meet estimated delivery dates. Buyer acknowledges these dates are estimates; Seller is not liable for any damages (including research delays or business interruption) resulting from early or late delivery.</p>'),
    jsonb_build_object('heading','2. Commencement of Lead Time','body','<p>Lead times commence only after all "Clearance Conditions" are met:</p><ul><li>Receipt of full payment (or down payment as specified in the quote).</li><li>Settlement of all technical specifications.</li><li>Receipt of all required export documentation and end-user certificates.</li></ul>'),
    jsonb_build_object('heading','3. Partial Shipments & Storage','body','<p>Seller is authorized to make partial shipments, each invoiced separately. If a shipment is delayed at the Buyer''s request, Seller may invoice immediately and charge for storage, insurance, and handling at the Buyer''s expense.</p>'),
    jsonb_build_object('heading','4. Shipping Terms (FCA Dallas)','body','<p>In accordance with FCA Dallas, Texas (Incoterms 2020):</p><ul><li><strong>Transfer of Title:</strong> Title and risk of loss pass to the Buyer the moment the Product is handed to the first carrier.</li><li><strong>Damage in Transit:</strong> Responsibility for loss or damage in transit lies with the Buyer. We strongly recommend that Buyers maintain adequate shipping insurance.</li></ul>'),
    jsonb_build_object('heading','5. Export Declarations & Compliance','body','<p>Max-IR Labs complies with all U.S. Export Administration Regulations (EAR).</p><ul><li><strong>Responsibility for Filing:</strong> Unless otherwise agreed in writing, the Buyer or the Buyer''s designated freight forwarder shall be responsible for filing all required U.S. export declarations (including Automated Export System / AES entries).</li><li><strong>Accuracy of Information:</strong> Seller will provide the necessary technical information (e.g., ECCN, HTS codes) to facilitate such filings. However, the Buyer warrants that all filings made by its agents will be accurate and in full compliance with U.S. law.</li><li><strong>Indemnification:</strong> Buyer shall defend, indemnify, and hold Max-IR Labs harmless from any fines, penalties, or legal costs arising from the Buyer''s (or its agent''s) failure to file correctly or comply with U.S. export/import regulations.</li><li><strong>Licensing:</strong> Some Products may require a specific U.S. export license. Buyer is responsible for providing all end-user information required to secure such licenses.</li></ul>'),
    jsonb_build_object('heading','6. International Duties & Taxes','body','<p>Buyer is the "Importer of Record" and is solely responsible for all import duties, customs clearance fees, and local taxes.</p>')
  )
)),
('terms-and-conditions', 'legal_document', 0, true, jsonb_build_object(
  'layout', 'legal_document',
  'title', 'Terms & Conditions of Sale',
  'effective_date', 'Effective Date: March 25, 2026',
  'intro', '',
  'sections', jsonb_build_array(
    jsonb_build_object('heading','1. Acceptance of Terms','body','<p>All sales by Max-IR Labs ("Seller") to any person or entity ("Buyer") are governed exclusively by these Terms and Conditions. Any additional or different terms proposed by Buyer in a purchase order are hereby rejected.</p>'),
    jsonb_build_object('heading','2. Pricing and Payment','body','<p>Proposals are valid for 30 days. For direct online sales, payment is due at checkout. For quote-based sales, payment terms are as specified in the individual quote; if no terms are specified, payment is due within thirty (30) days from the date of invoice. Seller reserves the right to require 100% prepayment (Cash in Advance) for any order. Late payments are subject to a 1.5% monthly charge plus collection costs and reasonable attorney fees.</p>'),
    jsonb_build_object('heading','3. Delivery (FCA)','body','<p>All Products are delivered FCA Seller''s Facility (Incoterms 2020). Title and risk of loss pass to Buyer upon delivery to the carrier. Delivery dates are estimates; Seller is not liable for shipping delays.</p>'),
    jsonb_build_object('heading','4. Limited Warranty & Consumables','body','<p>Seller warrants Products will meet published specifications at shipment. Warranty does not apply to parts consumed in normal operation (e.g., used waveguides) or products subjected to misuse, neglect, or improper storage.</p>'),
    jsonb_build_object('heading','5. Limitation of Liability','body','<p class="uppercase">Seller''s total liability shall not exceed the purchase price paid for the product. In no event shall seller be liable for loss of profits, data, or any consequential or incidental damages. Any legal action arising from a transaction must be commenced within one (1) year from the date of the alleged loss.</p>'),
    jsonb_build_object('heading','6. Intellectual Property & Reverse Engineering','body','<p>Seller retains all rights to patents, designs, and trade secrets. Buyer shall not copy, adapt, or reverse engineer any Product or software provided by Seller.</p>'),
    jsonb_build_object('heading','7. Export & Regulatory Compliance','body','<p>Buyer must comply with U.S. Export Administration Regulations. Seller makes no representation that Products conform to local ordinances or environmental regulations in the Buyer''s jurisdiction; compliance and any associated environmental costs are the sole responsibility of the Buyer.</p>'),
    jsonb_build_object('heading','8. Returns & Cancellation','body','<p>Custom or modified orders cannot be canceled. Standard returns require a Return Material Authorization (RMA) number. Buyer is responsible for return shipping costs.</p>'),
    jsonb_build_object('heading','9. Governing Law','body','<p>This agreement is governed by the laws of the State of Texas. Any disputes shall be resolved exclusively in the courts of Dallas County, Texas. The UN Convention on Contracts for the International Sale of Goods is expressly excluded.</p>'),
    jsonb_build_object('heading','10. Force Majeure','body','<p>Seller is not liable for failures to perform caused by events beyond its reasonable control, including natural disasters, supply chain shortages, or government actions.</p>')
  )
));